//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSSCDBI_5
{
    using System;
    using System.Collections.Generic;

    public partial class jny_app
    {
        public int local_id { get; set; }
        public Nullable<System.Guid> id { get; set; }
        public string name { get; set; }
        public string instance { get; set; }
        public string api_username { get; set; }
        public string api_password { get; set; }
        public string base_url { get; set; }
    }
}
