//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSSCDBI_5
{
    using System;
    using System.Collections.Generic;

    public partial class jny_worker
    {
        public int local_id { get; set; }
        public Nullable<System.DateTime> _updated_at { get; set; }
        public Nullable<System.Guid> current_area_id { get; set; }
        public Nullable<System.Guid> current_condition_id { get; set; }
        public Nullable<System.Guid> current_element_group_id { get; set; }
        public Nullable<System.Guid> current_element_id { get; set; }
        public Nullable<System.Guid> current_general_id { get; set; }
        public Nullable<System.Guid> current_material_id { get; set; }
        public Nullable<System.Guid> current_sub_area_id { get; set; }
        public string name { get; set; }
        public Nullable<int> next_previous { get; set; }
        public Nullable<System.Guid> id { get; set; }
        public string display_name { get; set; }
        public string enrolled { get; set; }
        public string barcode { get; set; }
        public string url { get; set; }
    }
}
