//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSSCDBI_5
{
    using System;
    using System.Collections.Generic;

    public partial class jny_photo_placeholder
    {
        public int local_id { get; set; }
        public Nullable<System.DateTime> _updated_at { get; set; }
        public Nullable<System.Guid> area_id { get; set; }
        public Nullable<System.Guid> condition_id { get; set; }
        public Nullable<System.Guid> element_id { get; set; }
        public Nullable<System.Guid> material_id { get; set; }
        public Nullable<System.Guid> site_id { get; set; }
        public Nullable<System.Guid> sub_area_id { get; set; }
        public Nullable<System.Guid> sync_site_id { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string altitude { get; set; }
        public string horizontal_accuracy { get; set; }
        public string vertical_accuracy { get; set; }
        public Nullable<System.Guid> id { get; set; }
        public string display_name { get; set; }
        public string thumbnail { get; set; }
        public string fullscreen { get; set; }
        public string original { get; set; }
        public string image_data { get; set; }
        public string image_mime_type { get; set; }
    }
}
